# Generated by Django 5.2.14 on 2026-05-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('watches', 'Luxury Watches'), ('smartphones', 'Flagship Smartphones'), ('fashion', 'Designer Fashion'), ('sneakers', 'Premium Sneakers'), ('jewelry', 'Elite Jewelry'), ('perfumes', 'Luxury Perfumes'), ('gadgets', 'Futuristic Gadgets'), ('headphones', 'High-End Headphones'), ('gaming', 'Luxury Gaming'), ('accessories', 'Exclusive Accessories')], max_length=30),
        ),
    ]
